### ISSUE TITLE
Doesn't render new property form correctly

### ISSUE THREAD

**Issue by joliveros** [TwilioDevEd/airtng-csharp-dotnet-core#2]
The page at `http://localhost:3000/properties/5bd3a1de22167764eb257dba` should render as shown below:

![image](https://user-images.githubusercontent.com/5973528/47596504-616bd980-d94c-11e8-8406-00b0fa5cf616.png)

compared to the following screenshot:
![image](https://user-images.githubusercontent.com/5973528/47596574-d50de680-d94c-11e8-8fb9-e6a8636a3be8.png)

Let me know if you need more info to reproduce.

**Comment by maylonpedroso** [comment]
@joliveros, I changed a bit the reservation process because I think the owner should not be able to make a reservation on his properties. That's why your property only has Edit and Delete actions available. I will change the render of the properties in the index view to make it look like in the old version and let you know to try again. Just a question, what version are you comparing with? That's no the asp .net original version, right?

**Comment by joliveros** [comment]
Hi @maylonpedroso 
I've been comparing against https://github.com/TwilioDevEd/airtng-node
which is the original tutorial I believe. The old asp.net may have been a little off.

**Comment by maylonpedroso** [comment]
Try this: https://github.com/TwilioDevEd/airtng-csharp-dotnet-core/pull/3
